apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432  # The port PostgreSQL listens on
  type: ClusterIP   # Exposes the service within the cluster only
